namespace RacingLeagueHub.Domain.Models.Constants;

public class Country
{
    public string Alpha2 { get; }
    public string Alpha3 { get; }
    public string Name { get; }

    public Country(string alpha2, string alpha3, string name)
    {
        Alpha2 = alpha3;
        Alpha3 = alpha3;
        Name = name;
    }
}

public static class Countries
{
    public static readonly Dictionary<string, Country> ByAlpha2 = new Dictionary<string, Country>
    {
        { "AF", new Country("AF", "AFG", "Afghanistan") },
        { "AX", new Country("AX", "ALA", "Åland Islands") },
        { "AL", new Country("AL", "ALB", "Albania") },
        { "DZ", new Country("DZ", "DZA", "Algeria") },
        { "AS", new Country("AS", "ASM", "American Samoa") },
        { "AD", new Country("AD", "AND", "Andorra") },
        { "AO", new Country("AO", "AGO", "Angola") },
        { "AI", new Country("AI", "AIA", "Anguilla") },
        { "AQ", new Country("AQ", "ATA", "Antarctica") },
        { "AG", new Country("AG", "ATG", "Antigua and Barbuda") },
        { "AR", new Country("AR", "ARG", "Argentina") },
        { "AM", new Country("AM", "ARM", "Armenia") },
        { "AW", new Country("AW", "ABW", "Aruba") },
        { "AU", new Country("AU", "AUS", "Australia") },
        { "AT", new Country("AT", "AUT", "Austria") },
        { "AZ", new Country("AZ", "AZE", "Azerbaijan") },
        { "BS", new Country("BS", "BHS", "Bahamas") },
        { "BH", new Country("BH", "BHR", "Bahrain") },
        { "BD", new Country("BD", "BGD", "Bangladesh") },
        { "BB", new Country("BB", "BRB", "Barbados") },
        { "BY", new Country("BY", "BLR", "Belarus") },
        { "BE", new Country("BE", "BEL", "Belgium") },
        { "BZ", new Country("BZ", "BLZ", "Belize") },
        { "BJ", new Country("BJ", "BEN", "Benin") },
        { "BM", new Country("BM", "BMU", "Bermuda") },
        { "BT", new Country("BT", "BTN", "Bhutan") },
        { "BO", new Country("BO", "BOL", "Bolivia, Plurinational State of") },
        { "BQ", new Country("BQ", "BES", "Bonaire, Sint Eustatius and Saba") },
        { "BA", new Country("BA", "BIH", "Bosnia and Herzegovina") },
        { "BW", new Country("BW", "BWA", "Botswana") },
        { "BV", new Country("BV", "BVT", "Bouvet Island") },
        { "BR", new Country("BR", "BRA", "Brazil") },
        { "IO", new Country("IO", "IOT", "British Indian Ocean Territory") },
        { "BN", new Country("BN", "BRN", "Brunei Darussalam") },
        { "BG", new Country("BG", "BGR", "Bulgaria") },
        { "BF", new Country("BF", "BFA", "Burkina Faso") },
        { "BI", new Country("BI", "BDI", "Burundi") },
        { "CV", new Country("CV", "CPV", "Cabo Verde") },
        { "KH", new Country("KH", "KHM", "Cambodia") },
        { "CM", new Country("CM", "CMR", "Cameroon") },
        { "CA", new Country("CA", "CAN", "Canada") },
        { "KY", new Country("KY", "CYM", "Cayman Islands") },
        { "CF", new Country("CF", "CAF", "Central African Republic") },
        { "TD", new Country("TD", "TCD", "Chad") },
        { "CL", new Country("CL", "CHL", "Chile") },
        { "CN", new Country("CN", "CHN", "China") },
        { "CX", new Country("CX", "CXR", "Christmas Island") },
        { "CC", new Country("CC", "CCK", "Cocos (Keeling) Islands") },
        { "CO", new Country("CO", "COL", "Colombia") },
        { "KM", new Country("KM", "COM", "Comoros") },
        { "CG", new Country("CG", "COG", "Congo") },
        { "CD", new Country("CD", "COD", "Congo, Democratic Republic of the") },
        { "CK", new Country("CK", "COK", "Cook Islands") },
        { "CR", new Country("CR", "CRI", "Costa Rica") },
        { "CI", new Country("CI", "CIV", "Côte d'Ivoire") },
        { "HR", new Country("HR", "HRV", "Croatia") },
        { "CU", new Country("CU", "CUB", "Cuba") },
        { "CW", new Country("CW", "CUW", "Curaçao") },
        { "CY", new Country("CY", "CYP", "Cyprus") },
        { "CZ", new Country("CZ", "CZE", "Czechia") },
        { "DK", new Country("DK", "DNK", "Denmark") },
        { "DJ", new Country("DJ", "DJI", "Djibouti") },
        { "DM", new Country("DM", "DMA", "Dominica") },
        { "DO", new Country("DO", "DOM", "Dominican Republic") },
        { "EC", new Country("EC", "ECU", "Ecuador") },
        { "EG", new Country("EG", "EGY", "Egypt") },
        { "SV", new Country("SV", "SLV", "El Salvador") },
        { "GQ", new Country("GQ", "GNQ", "Equatorial Guinea") },
        { "ER", new Country("ER", "ERI", "Eritrea") },
        { "EE", new Country("EE", "EST", "Estonia") },
        { "SZ", new Country("SZ", "SWZ", "Eswatini") },
        { "ET", new Country("ET", "ETH", "Ethiopia") },
        { "FK", new Country("FK", "FLK", "Falkland Islands (Malvinas)") },
        { "FO", new Country("FO", "FRO", "Faroe Islands") },
        { "FJ", new Country("FJ", "FJI", "Fiji") },
        { "FI", new Country("FI", "FIN", "Finland") },
        { "FR", new Country("FR", "FRA", "France") },
        { "GF", new Country("GF", "GUF", "French Guiana") },
        { "PF", new Country("PF", "PYF", "French Polynesia") },
        { "TF", new Country("TF", "ATF", "French Southern Territories") },
        { "GA", new Country("GA", "GAB", "Gabon") },
        { "GM", new Country("GM", "GMB", "Gambia") },
        { "GE", new Country("GE", "GEO", "Georgia") },
        { "DE", new Country("DE", "DEU", "Germany") },
        { "GH", new Country("GH", "GHA", "Ghana") },
        { "GI", new Country("GI", "GIB", "Gibraltar") },
        { "GR", new Country("GR", "GRC", "Greece") },
        { "GL", new Country("GL", "GRL", "Greenland") },
        { "GD", new Country("GD", "GRD", "Grenada") },
        { "GP", new Country("GP", "GLP", "Guadeloupe") },
        { "GU", new Country("GU", "GUM", "Guam") },
        { "GT", new Country("GT", "GTM", "Guatemala") },
        { "GG", new Country("GG", "GGY", "Guernsey") },
        { "GN", new Country("GN", "GIN", "Guinea") },
        { "GW", new Country("GW", "GNB", "Guinea-Bissau") },
        { "GY", new Country("GY", "GUY", "Guyana") },
        { "HT", new Country("HT", "HTI", "Haiti") },
        { "HM", new Country("HM", "HMD", "Heard Island and McDonald Islands") },
        { "VA", new Country("VA", "VAT", "Holy See") },
        { "HN", new Country("HN", "HND", "Honduras") },
        { "HK", new Country("HK", "HKG", "Hong Kong") },
        { "HU", new Country("HU", "HUN", "Hungary") },
        { "IS", new Country("IS", "ISL", "Iceland") },
        { "IN", new Country("IN", "IND", "India") },
        { "ID", new Country("ID", "IDN", "Indonesia") },
        { "IR", new Country("IR", "IRN", "Iran, Islamic Republic of") },
        { "IQ", new Country("IQ", "IRQ", "Iraq") },
        { "IE", new Country("IE", "IRL", "Ireland") },
        { "IM", new Country("IM", "IMN", "Isle of Man") },
        { "IL", new Country("IL", "ISR", "Israel") },
        { "IT", new Country("IT", "ITA", "Italy") },
        { "JM", new Country("JM", "JAM", "Jamaica") },
        { "JP", new Country("JP", "JPN", "Japan") },
        { "JE", new Country("JE", "JEY", "Jersey") },
        { "JO", new Country("JO", "JOR", "Jordan") },
        { "KZ", new Country("KZ", "KAZ", "Kazakhstan") },
        { "KE", new Country("KE", "KEN", "Kenya") },
        { "KI", new Country("KI", "KIR", "Kiribati") },
        { "KP", new Country("KP", "PRK", "Korea, Democratic People's Republic of") },
        { "KR", new Country("KR", "KOR", "Korea, Republic of") },
        { "KW", new Country("KW", "KWT", "Kuwait") },
        { "KG", new Country("KG", "KGZ", "Kyrgyzstan") },
        { "LA", new Country("LA", "LAO", "Lao People's Democratic Republic") },
        { "LV", new Country("LV", "LVA", "Latvia") },
        { "LB", new Country("LB", "LBN", "Lebanon") },
        { "LS", new Country("LS", "LSO", "Lesotho") },
        { "LR", new Country("LR", "LBR", "Liberia") },
        { "LY", new Country("LY", "LBY", "Libya") },
        { "LI", new Country("LI", "LIE", "Liechtenstein") },
        { "LT", new Country("LT", "LTU", "Lithuania") },
        { "LU", new Country("LU", "LUX", "Luxembourg") },
        { "MO", new Country("MO", "MAC", "Macao") },
        { "MG", new Country("MG", "MDG", "Madagascar") },
        { "MW", new Country("MW", "MWI", "Malawi") },
        { "MY", new Country("MY", "MYS", "Malaysia") },
        { "MV", new Country("MV", "MDV", "Maldives") },
        { "ML", new Country("ML", "MLI", "Mali") },
        { "MT", new Country("MT", "MLT", "Malta") },
        { "MH", new Country("MH", "MHL", "Marshall Islands") },
        { "MQ", new Country("MQ", "MTQ", "Martinique") },
        { "MR", new Country("MR", "MRT", "Mauritania") },
        { "MU", new Country("MU", "MUS", "Mauritius") },
        { "YT", new Country("YT", "MYT", "Mayotte") },
        { "MX", new Country("MX", "MEX", "Mexico") },
        { "FM", new Country("FM", "FSM", "Micronesia, Federated States of") },
        { "MD", new Country("MD", "MDA", "Moldova, Republic of") },
        { "MC", new Country("MC", "MCO", "Monaco") },
        { "MN", new Country("MN", "MNG", "Mongolia") },
        { "ME", new Country("ME", "MNE", "Montenegro") },
        { "MS", new Country("MS", "MSR", "Montserrat") },
        { "MA", new Country("MA", "MAR", "Morocco") },
        { "MZ", new Country("MZ", "MOZ", "Mozambique") },
        { "MM", new Country("MM", "MMR", "Myanmar") },
        { "NA", new Country("NA", "NAM", "Namibia") },
        { "NR", new Country("NR", "NRU", "Nauru") },
        { "NP", new Country("NP", "NPL", "Nepal") },
        { "NL", new Country("NL", "NLD", "Netherlands, Kingdom of the") },
        { "NC", new Country("NC", "NCL", "New Caledonia") },
        { "NZ", new Country("NZ", "NZL", "New Zealand") },
        { "NI", new Country("NI", "NIC", "Nicaragua") },
        { "NE", new Country("NE", "NER", "Niger") },
        { "NG", new Country("NG", "NGA", "Nigeria") },
        { "NU", new Country("NU", "NIU", "Niue") },
        { "NF", new Country("NF", "NFK", "Norfolk Island") },
        { "MK", new Country("MK", "MKD", "North Macedonia") },
        { "MP", new Country("MP", "MNP", "Northern Mariana Islands") },
        { "NO", new Country("NO", "NOR", "Norway") },
        { "OM", new Country("OM", "OMN", "Oman") },
        { "PK", new Country("PK", "PAK", "Pakistan") },
        { "PW", new Country("PW", "PLW", "Palau") },
        { "PS", new Country("PS", "PSE", "Palestine, State of") },
        { "PA", new Country("PA", "PAN", "Panama") },
        { "PG", new Country("PG", "PNG", "Papua New Guinea") },
        { "PY", new Country("PY", "PRY", "Paraguay") },
        { "PE", new Country("PE", "PER", "Peru") },
        { "PH", new Country("PH", "PHL", "Philippines") },
        { "PN", new Country("PN", "PCN", "Pitcairn") },
        { "PL", new Country("PL", "POL", "Poland") },
        { "PT", new Country("PT", "PRT", "Portugal") },
        { "PR", new Country("PR", "PRI", "Puerto Rico") },
        { "QA", new Country("QA", "QAT", "Qatar") },
        { "RE", new Country("RE", "REU", "Réunion") },
        { "RO", new Country("RO", "ROU", "Romania") },
        { "RU", new Country("RU", "RUS", "Russian Federation") },
        { "RW", new Country("RW", "RWA", "Rwanda") },
        { "BL", new Country("BL", "BLM", "Saint Barthélemy") },
        { "SH", new Country("SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha") },
        { "KN", new Country("KN", "KNA", "Saint Kitts and Nevis") },
        { "LC", new Country("LC", "LCA", "Saint Lucia") },
        { "MF", new Country("MF", "MAF", "Saint Martin (French part)") },
        { "PM", new Country("PM", "SPM", "Saint Pierre and Miquelon") },
        { "VC", new Country("VC", "VCT", "Saint Vincent and the Grenadines") },
        { "WS", new Country("WS", "WSM", "Samoa") },
        { "SM", new Country("SM", "SMR", "San Marino") },
        { "ST", new Country("ST", "STP", "Sao Tome and Principe") },
        { "SA", new Country("SA", "SAU", "Saudi Arabia") },
        { "SN", new Country("SN", "SEN", "Senegal") },
        { "RS", new Country("RS", "SRB", "Serbia") },
        { "SC", new Country("SC", "SYC", "Seychelles") },
        { "SL", new Country("SL", "SLE", "Sierra Leone") },
        { "SG", new Country("SG", "SGP", "Singapore") },
        { "SX", new Country("SX", "SXM", "Sint Maarten (Dutch part)") },
        { "SK", new Country("SK", "SVK", "Slovakia") },
        { "SI", new Country("SI", "SVN", "Slovenia") },
        { "SB", new Country("SB", "SLB", "Solomon Islands") },
        { "SO", new Country("SO", "SOM", "Somalia") },
        { "ZA", new Country("ZA", "ZAF", "South Africa") },
        { "GS", new Country("GS", "SGS", "South Georgia and the South Sandwich Islands") },
        { "SS", new Country("SS", "SSD", "South Sudan") },
        { "ES", new Country("ES", "ESP", "Spain") },
        { "LK", new Country("LK", "LKA", "Sri Lanka") },
        { "SD", new Country("SD", "SDN", "Sudan") },
        { "SR", new Country("SR", "SUR", "Suriname") },
        { "SJ", new Country("SJ", "SJM", "Svalbard and Jan Mayen") },
        { "SE", new Country("SE", "SWE", "Sweden") },
        { "CH", new Country("CH", "CHE", "Switzerland") },
        { "SY", new Country("SY", "SYR", "Syrian Arab Republic") },
        { "TW", new Country("TW", "TWN", "Taiwan, Province of China") },
        { "TJ", new Country("TJ", "TJK", "Tajikistan") },
        { "TZ", new Country("TZ", "TZA", "Tanzania, United Republic of") },
        { "TH", new Country("TH", "THA", "Thailand") },
        { "TL", new Country("TL", "TLS", "Timor-Leste") },
        { "TG", new Country("TG", "TGO", "Togo") },
        { "TK", new Country("TK", "TKL", "Tokelau") },
        { "TO", new Country("TO", "TON", "Tonga") },
        { "TT", new Country("TT", "TTO", "Trinidad and Tobago") },
        { "TN", new Country("TN", "TUN", "Tunisia") },
        { "TR", new Country("TR", "TUR", "Türkiye") },
        { "TM", new Country("TM", "TKM", "Turkmenistan") },
        { "TC", new Country("TC", "TCA", "Turks and Caicos Islands") },
        { "TV", new Country("TV", "TUV", "Tuvalu") },
        { "UG", new Country("UG", "UGA", "Uganda") },
        { "UA", new Country("UA", "UKR", "Ukraine") },
        { "AE", new Country("AE", "ARE", "United Arab Emirates") },
        { "GB", new Country("GB", "GBR", "United Kingdom of Great Britain and Northern Ireland") },
        { "US", new Country("US", "USA", "United States of America") },
        { "UM", new Country("UM", "UMI", "United States Minor Outlying Islands") },
        { "UY", new Country("UY", "URY", "Uruguay") },
        { "UZ", new Country("UZ", "UZB", "Uzbekistan") },
        { "VU", new Country("VU", "VUT", "Vanuatu") },
        { "VE", new Country("VE", "VEN", "Venezuela, Bolivarian Republic of") },
        { "VN", new Country("VN", "VNM", "Viet Nam") },
        { "VG", new Country("VG", "VGB", "Virgin Islands (British)") },
        { "VI", new Country("VI", "VIR", "Virgin Islands (U.S.)") },
        { "WF", new Country("WF", "WLF", "Wallis and Futuna") },
        { "EH", new Country("EH", "ESH", "Western Sahara") },
        { "YE", new Country("YE", "YEM", "Yemen") },
        { "ZM", new Country("ZM", "ZMB", "Zambia") },
        { "ZW", new Country("ZW", "ZWE", "Zimbabwe") },
    };
}