BEGIN;

INSERT INTO dc_country (id, code_alpha_2, code_alpha_3, name, is_active)
VALUES
    (1, 'AF', 'AFG', 'Afghanistan', true),
    (2, 'AL', 'ALB', 'Albania', true),
    (3, 'DZ', 'DZA', 'Algeria', true),
    (4, 'AS', 'ASM', 'American Samoa', true),
    (5, 'AD', 'AND', 'Andorra', true),
    (6, 'AO', 'AGO', 'Angola', true),
    (7, 'AI', 'AIA', 'Anguilla', true),
    (8, 'AQ', 'ATA', 'Antarctica', true),
    (9, 'AG', 'ATG', 'Antigua and Barbuda', true),
    (10, 'AR', 'ARG', 'Argentina', true),
    (11, 'AM', 'ARM', 'Armenia', true),
    (12, 'AW', 'ABW', 'Aruba', true),
    (13, 'AU', 'AUS', 'Australia', true),
    (14, 'AT', 'AUT', 'Austria', true),
    (15, 'AZ', 'AZE', 'Azerbaijan', true),
    (16, 'BS', 'BHS', 'Bahamas', true),
    (17, 'BH', 'BHR', 'Bahrain', true),
    (18, 'BD', 'BGD', 'Bangladesh', true),
    (19, 'BB', 'BRB', 'Barbados', true),
    (20, 'BY', 'BLR', 'Belarus', true),
    (21, 'BE', 'BEL', 'Belgium', true),
    (22, 'BZ', 'BLZ', 'Belize', true),
    (23, 'BJ', 'BEN', 'Benin', true),
    (24, 'BM', 'BMU', 'Bermuda', true),
    (25, 'BT', 'BTN', 'Bhutan', true),
    (26, 'BO', 'BOL', 'Bolivia', true),
    (27, 'BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', true),
    (28, 'BA', 'BIH', 'Bosnia and Herzegovina', true),
    (29, 'BW', 'BWA', 'Botswana', true),
    (30, 'BV', 'BVT', 'Bouvet Island', true),
    (31, 'BR', 'BRA', 'Brazil', true),
    (32, 'IO', 'IOT', 'British Indian Ocean Territory', true),
    (33, 'BN', 'BRN', 'Brunei Darussalam', true),
    (34, 'BG', 'BGR', 'Bulgaria', true),
    (35, 'BF', 'BFA', 'Burkina Faso', true),
    (36, 'BI', 'BDI', 'Burundi', true),
    (37, 'CV', 'CPV', 'Cabo Verde', true),
    (38, 'KH', 'KHM', 'Cambodia', true),
    (39, 'CM', 'CMR', 'Cameroon', true),
    (40, 'CA', 'CAN', 'Canada', true),
    (41, 'KY', 'CYM', 'Cayman Islands', true),
    (42, 'CF', 'CAF', 'Central African Republic', true),
    (43, 'TD', 'TCD', 'Chad', true),
    (44, 'CL', 'CHL', 'Chile', true),
    (45, 'CN', 'CHN', 'China', true),
    (46, 'CX', 'CXR', 'Christmas Island', true),
    (47, 'CC', 'CCK', 'Cocos (Keeling) Islands', true),
    (48, 'CO', 'COL', 'Colombia', true),
    (49, 'KM', 'COM', 'Comoros', true),
    (50, 'CG', 'COG', 'Congo', true),
    (51, 'CD', 'COD', 'Congo, The Democratic Republic of the', true),
    (52, 'CK', 'COK', 'Cook Islands', true),
    (53, 'CR', 'CRI', 'Costa Rica', true),
    (54, 'HR', 'HRV', 'Croatia', true),
    (55, 'CU', 'CUB', 'Cuba', true),
    (56, 'CW', 'CUW', 'Curaçao', true),
    (57, 'CY', 'CYP', 'Cyprus', true),
    (58, 'CZ', 'CZE', 'Czechia', true),
    (59, 'CI', 'CIV', 'Côte d''Ivoire', true),
    (60, 'DK', 'DNK', 'Denmark', true),
    (61, 'DJ', 'DJI', 'Djibouti', true),
    (62, 'DM', 'DMA', 'Dominica', true),
    (63, 'DO', 'DOM', 'Dominican Republic', true),
    (64, 'EC', 'ECU', 'Ecuador', true),
    (65, 'EG', 'EGY', 'Egypt', true),
    (66, 'SV', 'SLV', 'El Salvador', true),
    (67, 'GQ', 'GNQ', 'Equatorial Guinea', true),
    (68, 'ER', 'ERI', 'Eritrea', true),
    (69, 'EE', 'EST', 'Estonia', true),
    (70, 'SZ', 'SWZ', 'Eswatini', true),
    (71, 'ET', 'ETH', 'Ethiopia', true),
    (72, 'FK', 'FLK', 'Falkland Islands (Malvinas)', true),
    (73, 'FO', 'FRO', 'Faroe Islands', true),
    (74, 'FJ', 'FJI', 'Fiji', true),
    (75, 'FI', 'FIN', 'Finland', true),
    (76, 'FR', 'FRA', 'France', true),
    (77, 'GF', 'GUF', 'French Guiana', true),
    (78, 'PF', 'PYF', 'French Polynesia', true),
    (79, 'TF', 'ATF', 'French Southern Territories', true),
    (80, 'GA', 'GAB', 'Gabon', true),
    (81, 'GM', 'GMB', 'Gambia', true),
    (82, 'GE', 'GEO', 'Georgia', true),
    (83, 'DE', 'DEU', 'Germany', true),
    (84, 'GH', 'GHA', 'Ghana', true),
    (85, 'GI', 'GIB', 'Gibraltar', true),
    (86, 'GR', 'GRC', 'Greece', true),
    (87, 'GL', 'GRL', 'Greenland', true),
    (88, 'GD', 'GRD', 'Grenada', true),
    (89, 'GP', 'GLP', 'Guadeloupe', true),
    (90, 'GU', 'GUM', 'Guam', true),
    (91, 'GT', 'GTM', 'Guatemala', true),
    (92, 'GG', 'GGY', 'Guernsey', true),
    (93, 'GN', 'GIN', 'Guinea', true),
    (94, 'GW', 'GNB', 'Guinea-Bissau', true),
    (95, 'GY', 'GUY', 'Guyana', true),
    (96, 'HT', 'HTI', 'Haiti', true),
    (97, 'HM', 'HMD', 'Heard Island and McDonald Islands', true),
    (98, 'VA', 'VAT', 'Holy See (Vatican City State)', true),
    (99, 'HN', 'HND', 'Honduras', true),
    (100, 'HK', 'HKG', 'Hong Kong', true),
    (101, 'HU', 'HUN', 'Hungary', true),
    (102, 'IS', 'ISL', 'Iceland', true),
    (103, 'IN', 'IND', 'India', true),
    (104, 'ID', 'IDN', 'Indonesia', true),
    (105, 'IR', 'IRN', 'Iran', true),
    (106, 'IQ', 'IRQ', 'Iraq', true),
    (107, 'IE', 'IRL', 'Ireland', true),
    (108, 'IM', 'IMN', 'Isle of Man', true),
    (109, 'IL', 'ISR', 'Israel', true),
    (110, 'IT', 'ITA', 'Italy', true),
    (111, 'JM', 'JAM', 'Jamaica', true),
    (112, 'JP', 'JPN', 'Japan', true),
    (113, 'JE', 'JEY', 'Jersey', true),
    (114, 'JO', 'JOR', 'Jordan', true),
    (115, 'KZ', 'KAZ', 'Kazakhstan', true),
    (116, 'KE', 'KEN', 'Kenya', true),
    (117, 'KI', 'KIR', 'Kiribati', true),
    (118, 'KW', 'KWT', 'Kuwait', true),
    (119, 'KG', 'KGZ', 'Kyrgyzstan', true),
    (120, 'LA', 'LAO', 'Laos', true),
    (121, 'LV', 'LVA', 'Latvia', true),
    (122, 'LB', 'LBN', 'Lebanon', true),
    (123, 'LS', 'LSO', 'Lesotho', true),
    (124, 'LR', 'LBR', 'Liberia', true),
    (125, 'LY', 'LBY', 'Libya', true),
    (126, 'LI', 'LIE', 'Liechtenstein', true),
    (127, 'LT', 'LTU', 'Lithuania', true),
    (128, 'LU', 'LUX', 'Luxembourg', true),
    (129, 'MO', 'MAC', 'Macao', true),
    (130, 'MG', 'MDG', 'Madagascar', true),
    (131, 'MW', 'MWI', 'Malawi', true),
    (132, 'MY', 'MYS', 'Malaysia', true),
    (133, 'MV', 'MDV', 'Maldives', true),
    (134, 'ML', 'MLI', 'Mali', true),
    (135, 'MT', 'MLT', 'Malta', true),
    (136, 'MH', 'MHL', 'Marshall Islands', true),
    (137, 'MQ', 'MTQ', 'Martinique', true),
    (138, 'MR', 'MRT', 'Mauritania', true),
    (139, 'MU', 'MUS', 'Mauritius', true),
    (140, 'YT', 'MYT', 'Mayotte', true),
    (141, 'MX', 'MEX', 'Mexico', true),
    (142, 'FM', 'FSM', 'Micronesia, Federated States of', true),
    (143, 'MD', 'MDA', 'Moldova', true),
    (144, 'MC', 'MCO', 'Monaco', true),
    (145, 'MN', 'MNG', 'Mongolia', true),
    (146, 'ME', 'MNE', 'Montenegro', true),
    (147, 'MS', 'MSR', 'Montserrat', true),
    (148, 'MA', 'MAR', 'Morocco', true),
    (149, 'MZ', 'MOZ', 'Mozambique', true),
    (150, 'MM', 'MMR', 'Myanmar', true),
    (151, 'NA', 'NAM', 'Namibia', true),
    (152, 'NR', 'NRU', 'Nauru', true),
    (153, 'NP', 'NPL', 'Nepal', true),
    (154, 'NL', 'NLD', 'Netherlands', true),
    (155, 'NC', 'NCL', 'New Caledonia', true),
    (156, 'NZ', 'NZL', 'New Zealand', true),
    (157, 'NI', 'NIC', 'Nicaragua', true),
    (158, 'NE', 'NER', 'Niger', true),
    (159, 'NG', 'NGA', 'Nigeria', true),
    (160, 'NU', 'NIU', 'Niue', true),
    (161, 'NF', 'NFK', 'Norfolk Island', true),
    (162, 'KP', 'PRK', 'North Korea', true),
    (163, 'MK', 'MKD', 'North Macedonia', true),
    (164, 'MP', 'MNP', 'Northern Mariana Islands', true),
    (165, 'NO', 'NOR', 'Norway', true),
    (166, 'OM', 'OMN', 'Oman', true),
    (167, 'PK', 'PAK', 'Pakistan', true),
    (168, 'PW', 'PLW', 'Palau', true),
    (169, 'PS', 'PSE', 'Palestine, State of', true),
    (170, 'PA', 'PAN', 'Panama', true),
    (171, 'PG', 'PNG', 'Papua New Guinea', true),
    (172, 'PY', 'PRY', 'Paraguay', true),
    (173, 'PE', 'PER', 'Peru', true),
    (174, 'PH', 'PHL', 'Philippines', true),
    (175, 'PN', 'PCN', 'Pitcairn', true),
    (176, 'PL', 'POL', 'Poland', true),
    (177, 'PT', 'PRT', 'Portugal', true),
    (178, 'PR', 'PRI', 'Puerto Rico', true),
    (179, 'QA', 'QAT', 'Qatar', true),
    (180, 'RO', 'ROU', 'Romania', true),
    (181, 'RU', 'RUS', 'Russian Federation', true),
    (182, 'RW', 'RWA', 'Rwanda', true),
    (183, 'RE', 'REU', 'Réunion', true),
    (184, 'BL', 'BLM', 'Saint Barthélemy', true),
    (185, 'SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', true),
    (186, 'KN', 'KNA', 'Saint Kitts and Nevis', true),
    (187, 'LC', 'LCA', 'Saint Lucia', true),
    (188, 'MF', 'MAF', 'Saint Martin (French part)', true),
    (189, 'PM', 'SPM', 'Saint Pierre and Miquelon', true),
    (190, 'VC', 'VCT', 'Saint Vincent and the Grenadines', true),
    (191, 'WS', 'WSM', 'Samoa', true),
    (192, 'SM', 'SMR', 'San Marino', true),
    (193, 'ST', 'STP', 'Sao Tome and Principe', true),
    (194, 'SA', 'SAU', 'Saudi Arabia', true),
    (195, 'SN', 'SEN', 'Senegal', true),
    (196, 'RS', 'SRB', 'Serbia', true),
    (197, 'SC', 'SYC', 'Seychelles', true),
    (198, 'SL', 'SLE', 'Sierra Leone', true),
    (199, 'SG', 'SGP', 'Singapore', true),
    (200, 'SX', 'SXM', 'Sint Maarten (Dutch part)', true),
    (201, 'SK', 'SVK', 'Slovakia', true),
    (202, 'SI', 'SVN', 'Slovenia', true),
    (203, 'SB', 'SLB', 'Solomon Islands', true),
    (204, 'SO', 'SOM', 'Somalia', true),
    (205, 'ZA', 'ZAF', 'South Africa', true),
    (206, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', true),
    (207, 'KR', 'KOR', 'South Korea', true),
    (208, 'SS', 'SSD', 'South Sudan', true),
    (209, 'ES', 'ESP', 'Spain', true),
    (210, 'LK', 'LKA', 'Sri Lanka', true),
    (211, 'SD', 'SDN', 'Sudan', true),
    (212, 'SR', 'SUR', 'Suriname', true),
    (213, 'SJ', 'SJM', 'Svalbard and Jan Mayen', true),
    (214, 'SE', 'SWE', 'Sweden', true),
    (215, 'CH', 'CHE', 'Switzerland', true),
    (216, 'SY', 'SYR', 'Syria', true),
    (217, 'TW', 'TWN', 'Taiwan', true),
    (218, 'TJ', 'TJK', 'Tajikistan', true),
    (219, 'TZ', 'TZA', 'Tanzania', true),
    (220, 'TH', 'THA', 'Thailand', true),
    (221, 'TL', 'TLS', 'Timor-Leste', true),
    (222, 'TG', 'TGO', 'Togo', true),
    (223, 'TK', 'TKL', 'Tokelau', true),
    (224, 'TO', 'TON', 'Tonga', true),
    (225, 'TT', 'TTO', 'Trinidad and Tobago', true),
    (226, 'TN', 'TUN', 'Tunisia', true),
    (227, 'TM', 'TKM', 'Turkmenistan', true),
    (228, 'TC', 'TCA', 'Turks and Caicos Islands', true),
    (229, 'TV', 'TUV', 'Tuvalu', true),
    (230, 'TR', 'TUR', 'Türkiye', true),
    (231, 'UG', 'UGA', 'Uganda', true),
    (232, 'UA', 'UKR', 'Ukraine', true),
    (233, 'AE', 'ARE', 'United Arab Emirates', true),
    (234, 'GB', 'GBR', 'United Kingdom', true),
    (235, 'US', 'USA', 'United States', true),
    (236, 'UM', 'UMI', 'United States Minor Outlying Islands', true),
    (237, 'UY', 'URY', 'Uruguay', true),
    (238, 'UZ', 'UZB', 'Uzbekistan', true),
    (239, 'VU', 'VUT', 'Vanuatu', true),
    (240, 'VE', 'VEN', 'Venezuela', true),
    (241, 'VN', 'VNM', 'Vietnam', true),
    (242, 'VG', 'VGB', 'Virgin Islands, British', true),
    (243, 'VI', 'VIR', 'Virgin Islands, U.S.', true),
    (244, 'WF', 'WLF', 'Wallis and Futuna', true),
    (245, 'EH', 'ESH', 'Western Sahara', true),
    (246, 'YE', 'YEM', 'Yemen', true),
    (247, 'ZM', 'ZMB', 'Zambia', true),
    (248, 'ZW', 'ZWE', 'Zimbabwe', true),
    (249, 'AX', 'ALA', 'Åland Islands', true)
ON CONFLICT (id)
DO UPDATE SET
    code_alpha_2 = EXCLUDED.code_alpha_2,
    code_alpha_3 = EXCLUDED.code_alpha_3,
    name = EXCLUDED.name,
    is_active = EXCLUDED.is_active;

COMMIT;
