namespace RacingLeagueHub.BLL.Models.Constants;

public class Country
{
    public string Alpha3 { get; }
    public string Name { get; }

    public Country(string alpha3, string name)
    {
        Alpha3 = alpha3;
        Name = name;
    }
}

public static class Countries
{
    public static readonly Dictionary<string, Country> ByAlpha2 = new Dictionary<string, Country>
    {
        { "AF", new Country("AFG", "Afghanistan") },
        { "AX", new Country("ALA", "Åland Islands") },
        { "AL", new Country("ALB", "Albania") },
        { "DZ", new Country("DZA", "Algeria") },
        { "AS", new Country("ASM", "American Samoa") },
        { "AD", new Country("AND", "Andorra") },
        { "AO", new Country("AGO", "Angola") },
        { "AI", new Country("AIA", "Anguilla") },
        { "AQ", new Country("ATA", "Antarctica") },
        { "AG", new Country("ATG", "Antigua and Barbuda") },
        { "AR", new Country("ARG", "Argentina") },
        { "AM", new Country("ARM", "Armenia") },
        { "AW", new Country("ABW", "Aruba") },
        { "AU", new Country("AUS", "Australia") },
        { "AT", new Country("AUT", "Austria") },
        { "AZ", new Country("AZE", "Azerbaijan") },
        { "BS", new Country("BHS", "Bahamas") },
        { "BH", new Country("BHR", "Bahrain") },
        { "BD", new Country("BGD", "Bangladesh") },
        { "BB", new Country("BRB", "Barbados") },
        { "BY", new Country("BLR", "Belarus") },
        { "BE", new Country("BEL", "Belgium") },
        { "BZ", new Country("BLZ", "Belize") },
        { "BJ", new Country("BEN", "Benin") },
        { "BM", new Country("BMU", "Bermuda") },
        { "BT", new Country("BTN", "Bhutan") },
        { "BO", new Country("BOL", "Bolivia, Plurinational State of") },
        { "BQ", new Country("BES", "Bonaire, Sint Eustatius and Saba") },
        { "BA", new Country("BIH", "Bosnia and Herzegovina") },
        { "BW", new Country("BWA", "Botswana") },
        { "BV", new Country("BVT", "Bouvet Island") },
        { "BR", new Country("BRA", "Brazil") },
        { "IO", new Country("IOT", "British Indian Ocean Territory") },
        { "BN", new Country("BRN", "Brunei Darussalam") },
        { "BG", new Country("BGR", "Bulgaria") },
        { "BF", new Country("BFA", "Burkina Faso") },
        { "BI", new Country("BDI", "Burundi") },
        { "CV", new Country("CPV", "Cabo Verde") },
        { "KH", new Country("KHM", "Cambodia") },
        { "CM", new Country("CMR", "Cameroon") },
        { "CA", new Country("CAN", "Canada") },
        { "KY", new Country("CYM", "Cayman Islands") },
        { "CF", new Country("CAF", "Central African Republic") },
        { "TD", new Country("TCD", "Chad") },
        { "CL", new Country("CHL", "Chile") },
        { "CN", new Country("CHN", "China") },
        { "CX", new Country("CXR", "Christmas Island") },
        { "CC", new Country("CCK", "Cocos (Keeling) Islands") },
        { "CO", new Country("COL", "Colombia") },
        { "KM", new Country("COM", "Comoros") },
        { "CG", new Country("COG", "Congo") },
        { "CD", new Country("COD", "Congo, Democratic Republic of the") },
        { "CK", new Country("COK", "Cook Islands") },
        { "CR", new Country("CRI", "Costa Rica") },
        { "CI", new Country("CIV", "Côte d'Ivoire") },
        { "HR", new Country("HRV", "Croatia") },
        { "CU", new Country("CUB", "Cuba") },
        { "CW", new Country("CUW", "Curaçao") },
        { "CY", new Country("CYP", "Cyprus") },
        { "CZ", new Country("CZE", "Czechia") },
        { "DK", new Country("DNK", "Denmark") },
        { "DJ", new Country("DJI", "Djibouti") },
        { "DM", new Country("DMA", "Dominica") },
        { "DO", new Country("DOM", "Dominican Republic") },
        { "EC", new Country("ECU", "Ecuador") },
        { "EG", new Country("EGY", "Egypt") },
        { "SV", new Country("SLV", "El Salvador") },
        { "GQ", new Country("GNQ", "Equatorial Guinea") },
        { "ER", new Country("ERI", "Eritrea") },
        { "EE", new Country("EST", "Estonia") },
        { "SZ", new Country("SWZ", "Eswatini") },
        { "ET", new Country("ETH", "Ethiopia") },
        { "FK", new Country("FLK", "Falkland Islands (Malvinas)") },
        { "FO", new Country("FRO", "Faroe Islands") },
        { "FJ", new Country("FJI", "Fiji") },
        { "FI", new Country("FIN", "Finland") },
        { "FR", new Country("FRA", "France") },
        { "GF", new Country("GUF", "French Guiana") },
        { "PF", new Country("PYF", "French Polynesia") },
        { "TF", new Country("ATF", "French Southern Territories") },
        { "GA", new Country("GAB", "Gabon") },
        { "GM", new Country("GMB", "Gambia") },
        { "GE", new Country("GEO", "Georgia") },
        { "DE", new Country("DEU", "Germany") },
        { "GH", new Country("GHA", "Ghana") },
        { "GI", new Country("GIB", "Gibraltar") },
        { "GR", new Country("GRC", "Greece") },
        { "GL", new Country("GRL", "Greenland") },
        { "GD", new Country("GRD", "Grenada") },
        { "GP", new Country("GLP", "Guadeloupe") },
        { "GU", new Country("GUM", "Guam") },
        { "GT", new Country("GTM", "Guatemala") },
        { "GG", new Country("GGY", "Guernsey") },
        { "GN", new Country("GIN", "Guinea") },
        { "GW", new Country("GNB", "Guinea-Bissau") },
        { "GY", new Country("GUY", "Guyana") },
        { "HT", new Country("HTI", "Haiti") },
        { "HM", new Country("HMD", "Heard Island and McDonald Islands") },
        { "VA", new Country("VAT", "Holy See") },
        { "HN", new Country("HND", "Honduras") },
        { "HK", new Country("HKG", "Hong Kong") },
        { "HU", new Country("HUN", "Hungary") },
        { "IS", new Country("ISL", "Iceland") },
        { "IN", new Country("IND", "India") },
        { "ID", new Country("IDN", "Indonesia") },
        { "IR", new Country("IRN", "Iran, Islamic Republic of") },
        { "IQ", new Country("IRQ", "Iraq") },
        { "IE", new Country("IRL", "Ireland") },
        { "IM", new Country("IMN", "Isle of Man") },
        { "IL", new Country("ISR", "Israel") },
        { "IT", new Country("ITA", "Italy") },
        { "JM", new Country("JAM", "Jamaica") },
        { "JP", new Country("JPN", "Japan") },
        { "JE", new Country("JEY", "Jersey") },
        { "JO", new Country("JOR", "Jordan") },
        { "KZ", new Country("KAZ", "Kazakhstan") },
        { "KE", new Country("KEN", "Kenya") },
        { "KI", new Country("KIR", "Kiribati") },
        { "KP", new Country("PRK", "Korea, Democratic People's Republic of") },
        { "KR", new Country("KOR", "Korea, Republic of") },
        { "KW", new Country("KWT", "Kuwait") },
        { "KG", new Country("KGZ", "Kyrgyzstan") },
        { "LA", new Country("LAO", "Lao People's Democratic Republic") },
        { "LV", new Country("LVA", "Latvia") },
        { "LB", new Country("LBN", "Lebanon") },
        { "LS", new Country("LSO", "Lesotho") },
        { "LR", new Country("LBR", "Liberia") },
        { "LY", new Country("LBY", "Libya") },
        { "LI", new Country("LIE", "Liechtenstein") },
        { "LT", new Country("LTU", "Lithuania") },
        { "LU", new Country("LUX", "Luxembourg") },
        { "MO", new Country("MAC", "Macao") },
        { "MG", new Country("MDG", "Madagascar") },
        { "MW", new Country("MWI", "Malawi") },
        { "MY", new Country("MYS", "Malaysia") },
        { "MV", new Country("MDV", "Maldives") },
        { "ML", new Country("MLI", "Mali") },
        { "MT", new Country("MLT", "Malta") },
        { "MH", new Country("MHL", "Marshall Islands") },
        { "MQ", new Country("MTQ", "Martinique") },
        { "MR", new Country("MRT", "Mauritania") },
        { "MU", new Country("MUS", "Mauritius") },
        { "YT", new Country("MYT", "Mayotte") },
        { "MX", new Country("MEX", "Mexico") },
        { "FM", new Country("FSM", "Micronesia, Federated States of") },
        { "MD", new Country("MDA", "Moldova, Republic of") },
        { "MC", new Country("MCO", "Monaco") },
        { "MN", new Country("MNG", "Mongolia") },
        { "ME", new Country("MNE", "Montenegro") },
        { "MS", new Country("MSR", "Montserrat") },
        { "MA", new Country("MAR", "Morocco") },
        { "MZ", new Country("MOZ", "Mozambique") },
        { "MM", new Country("MMR", "Myanmar") },
        { "NA", new Country("NAM", "Namibia") },
        { "NR", new Country("NRU", "Nauru") },
        { "NP", new Country("NPL", "Nepal") },
        { "NL", new Country("NLD", "Netherlands, Kingdom of the") },
        { "NC", new Country("NCL", "New Caledonia") },
        { "NZ", new Country("NZL", "New Zealand") },
        { "NI", new Country("NIC", "Nicaragua") },
        { "NE", new Country("NER", "Niger") },
        { "NG", new Country("NGA", "Nigeria") },
        { "NU", new Country("NIU", "Niue") },
        { "NF", new Country("NFK", "Norfolk Island") },
        { "MK", new Country("MKD", "North Macedonia") },
        { "MP", new Country("MNP", "Northern Mariana Islands") },
        { "NO", new Country("NOR", "Norway") },
        { "OM", new Country("OMN", "Oman") },
        { "PK", new Country("PAK", "Pakistan") },
        { "PW", new Country("PLW", "Palau") },
        { "PS", new Country("PSE", "Palestine, State of") },
        { "PA", new Country("PAN", "Panama") },
        { "PG", new Country("PNG", "Papua New Guinea") },
        { "PY", new Country("PRY", "Paraguay") },
        { "PE", new Country("PER", "Peru") },
        { "PH", new Country("PHL", "Philippines") },
        { "PN", new Country("PCN", "Pitcairn") },
        { "PL", new Country("POL", "Poland") },
        { "PT", new Country("PRT", "Portugal") },
        { "PR", new Country("PRI", "Puerto Rico") },
        { "QA", new Country("QAT", "Qatar") },
        { "RE", new Country("REU", "Réunion") },
        { "RO", new Country("ROU", "Romania") },
        { "RU", new Country("RUS", "Russian Federation") },
        { "RW", new Country("RWA", "Rwanda") },
        { "BL", new Country("BLM", "Saint Barthélemy") },
        { "SH", new Country("SHN", "Saint Helena, Ascension and Tristan da Cunha") },
        { "KN", new Country("KNA", "Saint Kitts and Nevis") },
        { "LC", new Country("LCA", "Saint Lucia") },
        { "MF", new Country("MAF", "Saint Martin (French part)") },
        { "PM", new Country("SPM", "Saint Pierre and Miquelon") },
        { "VC", new Country("VCT", "Saint Vincent and the Grenadines") },
        { "WS", new Country("WSM", "Samoa") },
        { "SM", new Country("SMR", "San Marino") },
        { "ST", new Country("STP", "Sao Tome and Principe") },
        { "SA", new Country("SAU", "Saudi Arabia") },
        { "SN", new Country("SEN", "Senegal") },
        { "RS", new Country("SRB", "Serbia") },
        { "SC", new Country("SYC", "Seychelles") },
        { "SL", new Country("SLE", "Sierra Leone") },
        { "SG", new Country("SGP", "Singapore") },
        { "SX", new Country("SXM", "Sint Maarten (Dutch part)") },
        { "SK", new Country("SVK", "Slovakia") },
        { "SI", new Country("SVN", "Slovenia") },
        { "SB", new Country("SLB", "Solomon Islands") },
        { "SO", new Country("SOM", "Somalia") },
        { "ZA", new Country("ZAF", "South Africa") },
        { "GS", new Country("SGS", "South Georgia and the South Sandwich Islands") },
        { "SS", new Country("SSD", "South Sudan") },
        { "ES", new Country("ESP", "Spain") },
        { "LK", new Country("LKA", "Sri Lanka") },
        { "SD", new Country("SDN", "Sudan") },
        { "SR", new Country("SUR", "Suriname") },
        { "SJ", new Country("SJM", "Svalbard and Jan Mayen") },
        { "SE", new Country("SWE", "Sweden") },
        { "CH", new Country("CHE", "Switzerland") },
        { "SY", new Country("SYR", "Syrian Arab Republic") },
        { "TW", new Country("TWN", "Taiwan, Province of China") },
        { "TJ", new Country("TJK", "Tajikistan") },
        { "TZ", new Country("TZA", "Tanzania, United Republic of") },
        { "TH", new Country("THA", "Thailand") },
        { "TL", new Country("TLS", "Timor-Leste") },
        { "TG", new Country("TGO", "Togo") },
        { "TK", new Country("TKL", "Tokelau") },
        { "TO", new Country("TON", "Tonga") },
        { "TT", new Country("TTO", "Trinidad and Tobago") },
        { "TN", new Country("TUN", "Tunisia") },
        { "TR", new Country("TUR", "Türkiye") },
        { "TM", new Country("TKM", "Turkmenistan") },
        { "TC", new Country("TCA", "Turks and Caicos Islands") },
        { "TV", new Country("TUV", "Tuvalu") },
        { "UG", new Country("UGA", "Uganda") },
        { "UA", new Country("UKR", "Ukraine") },
        { "AE", new Country("ARE", "United Arab Emirates") },
        { "GB", new Country("GBR", "United Kingdom of Great Britain and Northern Ireland") },
        { "US", new Country("USA", "United States of America") },
        { "UM", new Country("UMI", "United States Minor Outlying Islands") },
        { "UY", new Country("URY", "Uruguay") },
        { "UZ", new Country("UZB", "Uzbekistan") },
        { "VU", new Country("VUT", "Vanuatu") },
        { "VE", new Country("VEN", "Venezuela, Bolivarian Republic of") },
        { "VN", new Country("VNM", "Viet Nam") },
        { "VG", new Country("VGB", "Virgin Islands (British)") },
        { "VI", new Country("VIR", "Virgin Islands (U.S.)") },
        { "WF", new Country("WLF", "Wallis and Futuna") },
        { "EH", new Country("ESH", "Western Sahara") },
        { "YE", new Country("YEM", "Yemen") },
        { "ZM", new Country("ZMB", "Zambia") },
        { "ZW", new Country("ZWE", "Zimbabwe") },
    };
}